trigger:
- main

pool:
  vmImage: 'windows-latest'


variables:
  projectdir: 'qa-portfolio-juliana/ui-api-token'
  projectPath: 'qa-portfolio-juliana/ui-api-token'
  NODE_VERSION: '20.x'
  NPM_CACHE_FOLDER: '$(Pipeline.Workspace)/.npm'
  PLAYWRIGHT_BROWSERS_PATH: '$(Pipeline.Workspace)/.pw-browsers'

steps:
- checkout: self

  - powershell: |
    Write-Host "Raiz do repositório:"
    Get-ChildItem "$(Build.SourcesDirectory)" -Force

    $proj = "$(Build.SourcesDirectory)/ui-api-token"
    Write-Host "Tentando entrar em: $proj"

    if (!(Test-Path $proj)) {
      Write-Error "❌ Pasta ui-api-token NÃO encontrada"
      exit 1
    }

    Set-Location $proj
    Write-Host "✅ Estou dentro da pasta do projeto:"
    pwd
    Get-ChildItem -Force
  displayName: "PASSO B - Entrar na pasta ui-api-token"

  - powershell: |
    Set-Location "$(Build.SourcesDirectory)/ui-api-token"
    npm ci
  displayName: "PASSO C - Instalar dependências (npm ci)"

  - powershell: |
    Set-Location "$(Build.SourcesDirectory)/ui-api-token"
    npx playwright test
  displayName: "PASSO D - Executar testes Playwright"
  condition: succeededOrFailed()
